/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "STM32f446xx.h"
#include "STM32f446xx_GPIO.h"



int main2 (void)
{

    GPIO_Handle_t gpioLED;
    memset(&gpioLED, 0, sizeof(gpioLED));

    gpioLED.pGPIOx = GPIOA;

    // Configure the GPIO Device
    gpioLED.GPIO_PinConfig.GPIO_PinNumber = 5;
    gpioLED.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_OUT;
    gpioLED.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FA;
    gpioLED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_PP;

    // Enable the registers clock
    GPIO_ClockCtl(gpioLED.pGPIOx, ENABLE);

    // Initialize the device
    GPIO_Init(&gpioLED);

    /* Loop forever */
	while(1){

        // Toggle the pin!
        GPIO_TogglePin(gpioLED.pGPIOx, 5);
        delay((uint32_t) 1);
    }

    return 0;
}
